### ISSUE TITLE
multiple definition of 'TAG'

### ISSUE THREAD

**Issue by robertoimai** [espressif/esp-avs-sdk#28]
I'm using release/v3.1 and I'm getting this error when trying to build:
LD build/azena_glass2_production.elf
/home/owner/Dropbox/Azena/Glass2/ESP32/Azena_Glass2_Production/build/spiffs/libspiffs.a(spiffs_api.o):(.data.TAG+0x0): multiple definition of `TAG'
/home/owner/esp/esp-avs-sdk/components/speech_recog/lib/libesp_wwe.a(esp_wwe.o):(.data.TAG+0x0): first defined here
collect2: error: ld returned 1 exit status
/home/owner/esp/esp-idf/make/project.mk:406: recipe for target '/home/owner/Dropbox/Azena/Glass2/ESP32/Azena_Glass2_Production/build/azena_glass2_production.elf' failed
make: *** [/home/owner/Dropbox/Azena/Glass2/ESP32/Azena_Glass2_Production/build/azena_glass2_production.elf] Error 1

**Comment by robertoimai** [comment]
This issue disappeared when I updated IDF to 3.2
